lang["SERVER_NAME"]["en"] <- "Memory";
lang["LABEL_LOGIN_MENU_USERNAME"]["en"] <- "Username";
lang["LABEL_LOGIN_MENU_PASSWORD"]["en"] <- "Password";
lang["LABEL_REGISTER_MENU_PASSWORD"]["en"] <- "Password";
lang["LABEL_REGISTER_MENU_CPASSWORD"]["en"] <- "Confirm password";
lang["BUTTON_REGISTER_MENU_OK"]["en"] <- "Ok";
lang["BUTTON_REGISTER_MENU_BACK"]["en"] <- "Back";
lang["BUTTON_LOGIN_MENU_QUIT"]["en"] <- "Quit";
lang["BUTTON_LOGIN_MENU_OK"]["en"] <- "Ok";
lang["CHECKBOX_LOGIN_REMEMBER"]["en"] <- "Remember me";
lang["REGISTER_YOURSELF"]["en"] <- "Create account";
lang["DONT_HAVE_ACCOUNT"]["en"] <- "Don't have an account?";
lang["LABEL_REGISTER_MENU_USERNAME"]["en"] <- "Username";
lang["LABEL_CHAR_SELECTION_MENU_CHARACTERS"]["en"] <- "Characters";
lang["LABEL_CHAR_SELECTION_MENU_SLOT1"]["en"] <- "(Slot 1)";
lang["LABEL_CHAR_SELECTION_MENU_SLOT2"]["en"] <- "(Slot 2)";
lang["LABEL_CHAR_SELECTION_MENU_SLOT3"]["en"] <- "(Slot 3)";
lang["BUTTON_CHAR_SELECTION_MENU_OK"]["en"] <- "Play";
lang["BUTTON_CHAR_SELECTION_MENU_CREATE"]["en"] <- "Create";
lang["BUTTON_CHAR_SELECTION_MENU_SELECT"]["en"] <- "Select";
lang["BUTTON_CHAR_SELECTION_MENU_LOGOUT"]["en"] <- "Log out";
lang["BUTTON_CHAR_SELECTION_MENU_QUIT"]["en"] <- "Quit";
lang["BUTTON_CHAR_SELECTION_MENU_NEWCHAR"]["en"] <- "+ New character";
lang["LABEL_CREATION_TITLE"]["en"] <- "Creation";
lang["LABEL_CREATION_NAME"]["en"] <- "Name:";
lang["LABEL_CREATION_MALE"]["en"] <- "Male";
lang["LABEL_CREATION_FEMALE"]["en"] <- "Female";
lang["LABEL_CREATION_SEX"]["en"] <- "Sex";
lang["LABEL_CREATION_BODYTEX"]["en"] <- "Body texture";
lang["LABEL_CREATION_HEADMODEL"]["en"] <- "Head model";
lang["LABEL_CREATION_HEADTEX"]["en"] <- "Head texture";
lang["LABEL_CREATION_FATNESS"]["en"] <- "Fatness";
lang["LABEL_CREATION_WALKINGSTYLE"]["en"] <- "Walking style";
lang["BUTTON_CREATION_OK"]["en"] <- "Create";
lang["BUTTON_CREATION_BACK"]["en"] <- "Go back";
lang["PLACEHOLDER_CHARNAME"]["en"] <- "Character name";
lang["INV_USE"]["en"] <- "Use";
lang["INV_DROP"]["en"] <- "Drop";
lang["INV_NONUSABLE"]["en"] <- "Non usable";
lang["INV_EQUIP"]["en"] <- "Equip";
lang["INV_UNEQUIP"]["en"] <- "Unequip";
lang["LEVEL_UP"]["en"] <- "Level up";
lang["ADD_EXPERIENCE"]["en"] <- "Experience +";
lang["VALUE"]["en"] <- "Value: ";
lang["SHOP"]["en"] <- "Shop";
lang["ORE"]["en"] <- "Ore: ";
lang["MY_INVENTORY"]["en"] <- "My inventory";
lang["PRICE"]["en"] <- "Price: ";
lang["TRADE_SUCCESS"]["en"] <- "Trade successful";
lang["TRADE_LITTLE_ORES"]["en"] <- "Not enough ores!";
lang["TRADE"]["en"] <- "Trade";
lang["EXIT"]["en"] <- "Exit";
lang["ENTER_AMOUNT"]["en"] <- "Enter the amount of";
lang["TRADEBOX_OK"]["en"] <- "Ok";
lang["TRADEBOX_CANCEL"]["en"] <- "Cancel";
lang["INV_ARMOR"]["en"] <- "Armor";
lang["INV_WEAPON"]["en"] <- "Weapons";
lang["INV_QA"]["en"] <- "Quick access";
lang["STATISTICS"]["en"] <- "Statistics";
lang["ESC_INFO"]["en"] <- "(ESC) Press to resume";
lang["NAME"]["en"] <- "Name";
lang["LEVEL"]["en"] <- "Level";
lang["EXPERIENCE"]["en"] <- "Experience";
lang["HEALTH"]["en"] <- "Health";
lang["MANA"]["en"] <- "Mana";
lang["STRENGTH"]["en"] <- "Strength";
lang["DEXTERITY"]["en"] <- "Dexterity";
lang["SKILL_1H"]["en"] <- "One-handed fight";
lang["SKILL_2H"]["en"] <- "Two-handed fight";
lang["SKILL_BOW"]["en"] <- "Bow fight";
lang["SKILL_CBOW"]["en"] <- "Crossbow fight";
lang["MAGIC_LEVEL"]["en"] <- "Magic level";
lang["GUARDIAN"]["en"] <- "Guardian";
lang["TRADER"]["en"] <- "Trader";
lang["SCAVENGER"]["en"] <- "Scavenger";
lang["CTRL"]["en"] <- "(CTRL)";
lang["TALK"]["en"] <- "Talk";
lang["TAKE"]["en"] <- "Take";
lang["GET_OUT"]["en"] <- "Get out of here!";
lang["RESPAWN_INFO"]["en"] <- "You are going to respawn in ";
lang["ADD_GOLD"]["en"] <- "Ore +";
lang["DEFAULT"]["en"] <- "Default";
lang["ARROGANCE"]["en"] <- "Arrogance";
lang["BABE"]["en"] <- "Babe";
lang["FLEE"]["en"] <- "Flee";
lang["MAGE"]["en"] <- "Mage";
lang["MILITIA"]["en"] <- "Militia";
lang["RELAXED"]["en"] <- "Relaxed";
lang["TIRED"]["en"] <- "Tired";
lang["PROGRESS"]["en"] <- "Progress";
lang["ATTRIBUTES"]["en"] <- "Attributes";
lang["SKILLS"]["en"] <- "Skills";
lang["SAVE"]["en"] <- "Save";
lang["RESTORE"]["en"] <- "Restore";
lang["CHAR_DESC"]["en"] <- "Character description";
lang["NEXT_LEVEL"]["en"] <- "Next level";
lang["APPLY"]["en"] <- "Apply";
lang["CANCEL"]["en"] <- "Cancel";
lang["VIDEO_SETTINGS"]["en"] <- "Video settings";
lang["SIGHT_FACTOR"]["en"] <- "Sight factor";
lang["LOD_STRENGTH_MODIFIER"]["en"] <- "Level of detail";
lang["DETAIL_RENDER_DISTANCE"]["en"] <- "Level of detail modifier";
lang["AUDIO_SETTINGS"]["en"] <- "Audio settings";
lang["MUSIC_VOLUME"]["en"] <- "Music volume";
lang["SOUND_VOLUME"]["en"] <- "Sound volume";
lang["RESOLUTION"]["en"] <- "Resolution";
lang["ITEMS"]["en"] <- "Items";
lang["RESUME"]["en"] <- "Resume";
lang["MAP"]["en"] <- "Map";
lang["INVENTORY"]["en"] <- "Inventory";
lang["CHARACTER"]["en"] <- "Character";
lang["SETTINGS"]["en"] <- "Settings";
lang["QUIT"]["en"] <- "Quit";
lang["INV_OPEN"]["en"] <- "Open";
lang["SKILL_POINTS"]["en"] <- "Skill points";
lang["TRAINER"]["en"] <- "Trainer";
