lang["SERVER_NAME"]["pl"] <- "Memory";
lang["LABEL_LOGIN_MENU_USERNAME"]["pl"] <- "Login";
lang["LABEL_LOGIN_MENU_PASSWORD"]["pl"] <- "Has³o";
lang["LABEL_REGISTER_MENU_PASSWORD"]["pl"] <- "Has³o";
lang["LABEL_REGISTER_MENU_CPASSWORD"]["pl"] <- "Powtórz has³o";
lang["BUTTON_REGISTER_MENU_OK"]["pl"] <- "Ok";
lang["BUTTON_REGISTER_MENU_BACK"]["pl"] <- "Wróæ";
lang["BUTTON_LOGIN_MENU_QUIT"]["pl"] <- "WyjdŸ";
lang["BUTTON_LOGIN_MENU_OK"]["pl"] <- "Ok";
lang["CHECKBOX_LOGIN_REMEMBER"]["pl"] <- "Zapamiêtaj mnie";
lang["REGISTER_YOURSELF"]["pl"] <- "Zarejestruj siê";
lang["DONT_HAVE_ACCOUNT"]["pl"] <- "Nie masz konta?";
lang["LABEL_REGISTER_MENU_USERNAME"]["pl"] <- "Login";
lang["LABEL_CHAR_SELECTION_MENU_CHARACTERS"]["pl"] <- "Postacie";
lang["LABEL_CHAR_SELECTION_MENU_SLOT1"]["pl"] <- "(Slot 1)";
lang["LABEL_CHAR_SELECTION_MENU_SLOT2"]["pl"] <- "(Slot 2)";
lang["LABEL_CHAR_SELECTION_MENU_SLOT3"]["pl"] <- "(Slot 3)";
lang["BUTTON_CHAR_SELECTION_MENU_OK"]["pl"] <- "Graj";
lang["BUTTON_CHAR_SELECTION_MENU_CREATE"]["pl"] <- "Stwórz";
lang["BUTTON_CHAR_SELECTION_MENU_SELECT"]["pl"] <- "Wybierz";
lang["BUTTON_CHAR_SELECTION_MENU_LOGOUT"]["pl"] <- "Wyloguj";
lang["BUTTON_CHAR_SELECTION_MENU_QUIT"]["pl"] <- "WyjdŸ";
lang["BUTTON_CHAR_SELECTION_MENU_NEWCHAR"]["pl"] <- "+ Nowa postaæ";
lang["LABEL_CREATION_TITLE"]["pl"] <- "Kreacja";
lang["LABEL_CREATION_NAME"]["pl"] <- "Imiê:";
lang["LABEL_CREATION_MALE"]["pl"] <- "Mê¿czyzna";
lang["LABEL_CREATION_FEMALE"]["pl"] <- "Kobieta";
lang["LABEL_CREATION_SEX"]["pl"] <- "P³eæ";
lang["LABEL_CREATION_BODYTEX"]["pl"] <- "Tekstura cia³a";
lang["LABEL_CREATION_HEADMODEL"]["pl"] <- "Model g³owy";
lang["LABEL_CREATION_HEADTEX"]["pl"] <- "Tekstura g³owy";
lang["LABEL_CREATION_FATNESS"]["pl"] <- "Oty³oœæ";
lang["LABEL_CREATION_WALKINGSTYLE"]["pl"] <- "Styl chodzenia";
lang["BUTTON_CREATION_OK"]["pl"] <- "Stwórz";
lang["BUTTON_CREATION_BACK"]["pl"] <- "Wróæ";
lang["PLACEHOLDER_CHARNAME"]["pl"] <- "Imiê postaci";
lang["INV_USE"]["pl"] <- "U¿yj";
lang["INV_DROP"]["pl"] <- "Wyrzuæ";
lang["INV_NONUSABLE"]["pl"] <- "Bez u¿yteczne";
lang["INV_EQUIP"]["pl"] <- "Za³ó¿";
lang["INV_UNEQUIP"]["pl"] <- "Zdejmij";
lang["LEVEL_UP"]["pl"] <- "Kolejny poziom";
lang["ADD_EXPERIENCE"]["pl"] <- "Doœwiadczenie +";
lang["VALUE"]["pl"] <- "Wartoœæ: ";
lang["SHOP"]["pl"] <- "Sklep";
lang["ORE"]["pl"] <- "Ruda: ";
lang["MY_INVENTORY"]["pl"] <- "Mój ekwipunek";
lang["PRICE"]["pl"] <- "Cena: ";
lang["TRADE_SUCCESS"]["pl"] <- "Handel pomyœlny";
lang["TRADE_LITTLE_ORES"]["pl"] <- "Za ma³o rudy!";
lang["TRADE"]["pl"] <- "Handel";
lang["EXIT"]["pl"] <- "WyjdŸ";
lang["ENTER_AMOUNT"]["pl"] <- "WprowadŸ iloœæ";
lang["TRADEBOX_OK"]["pl"] <- "Ok";
lang["TRADEBOX_CANCEL"]["pl"] <- "Anuluj";
lang["INV_ARMOR"]["pl"] <- "Zbroja";
lang["INV_WEAPON"]["pl"] <- "Bronie";
lang["INV_QA"]["pl"] <- "Szybki dostêp";
lang["STATISTICS"]["pl"] <- "Statystyki";
lang["ESC_INFO"]["pl"] <- "(ESC) Wciœnij by powróciæ";
lang["NAME"]["pl"] <- "Imiê";
lang["LEVEL"]["pl"] <- "Poziom";
lang["EXPERIENCE"]["pl"] <- "Doœwiadczenie";
lang["HEALTH"]["pl"] <- "¯ycie";
lang["MANA"]["pl"] <- "Mana";
lang["STRENGTH"]["pl"] <- "Si³a";
lang["DEXTERITY"]["pl"] <- "Zwinnoœæ";
lang["SKILL_1H"]["pl"] <- "Walka broni¹ jednorêczn¹";
lang["SKILL_2H"]["pl"] <- "Walka broni¹ dwurêczn¹";
lang["SKILL_BOW"]["pl"] <- "Walka ³ukiem";
lang["SKILL_CBOW"]["pl"] <- "Walka kusz¹";
lang["MAGIC_LEVEL"]["pl"] <- "Kr¹g magii";
lang["GUARDIAN"]["pl"] <- "Stra¿nik";
lang["TRADER"]["pl"] <- "Handlarz";
lang["SCAVENGER"]["pl"] <- "Œcierwojad";
lang["CTRL"]["pl"] <- "(CTRL)";
lang["TALK"]["pl"] <- "Porozmawiaj";
lang["TAKE"]["pl"] <- "Podnieœ";
lang["GET_OUT"]["pl"] <- "Spadaj st¹d!";
lang["RESPAWN_INFO"]["pl"] <- "Odrodzisz siê za ";
lang["ADD_GOLD"]["pl"] <- "Ruda +";
lang["DEFAULT"]["pl"] <- "Domyœlny";
lang["ARROGANCE"]["pl"] <- "Arogancki";
lang["BABE"]["pl"] <- "Kobiecy";
lang["FLEE"]["pl"] <- "Pospieszny";
lang["MAGE"]["pl"] <- "Mag";
lang["MILITIA"]["pl"] <- "¯o³nierski";
lang["RELAXED"]["pl"] <- "Wyluzowany";
lang["TIRED"]["pl"] <- "Zmêczony";
lang["PROGRESS"]["pl"] <- "Postêp";
lang["ATTRIBUTES"]["pl"] <- "Atrybuty";
lang["SKILLS"]["pl"] <- "Umiejêtnoœci";
lang["SAVE"]["pl"] <- "Zapisz";
lang["RESTORE"]["pl"] <- "Przywróæ";
lang["CHAR_DESC"]["pl"] <- "Opis postaci";
lang["NEXT_LEVEL"]["pl"] <- "Nastêpny poziom";
lang["APPLY"]["pl"] <- "ZatwierdŸ";
lang["CANCEL"]["pl"] <- "Anuluj";
lang["VIDEO_SETTINGS"]["pl"] <- "Ustawienia wideo";
lang["SIGHT_FACTOR"]["pl"] <- "Zasiêg widzenia";
lang["LOD_STRENGTH_MODIFIER"]["pl"] <- "Poziom detali";
lang["DETAIL_RENDER_DISTANCE"]["pl"] <- "Modyfikator poziomu detali";
lang["AUDIO_SETTINGS"]["pl"] <- "Ustawienia dŸwiêku";
lang["MUSIC_VOLUME"]["pl"] <- "G³oœnoœæ muzyki";
lang["SOUND_VOLUME"]["pl"] <- "G³oœnoœæ dŸwiêku";
lang["RESOLUTION"]["pl"] <- "Rozdzielczoœæ";
lang["ITEMS"]["pl"] <- "Przedmioty";
lang["RESUME"]["pl"] <- "Wznów";
lang["MAP"]["pl"] <- "Mapa";
lang["INVENTORY"]["pl"] <- "Ekwipunek";
lang["CHARACTER"]["pl"] <- "Postaæ";
lang["SETTINGS"]["pl"] <- "Ustawienia";
lang["QUIT"]["pl"] <- "WyjdŸ";
lang["INV_OPEN"]["pl"] <- "Otwórz";
lang["SKILL_POINTS"]["pl"] <- "Punkty nauki";
lang["TRAINER"]["pl"] <- "Trener";
lang["REAL_TIME"]["pl"] <- "Czas realny: ";
lang["INGAME_TIME"]["pl"] <- "Czas w grze: ";
lang["PLAYER_LIST"]["pl"] <- "Lista graczy";
lang["HELP"]["pl"] <- "Pomoc";
lang["ID"]["pl"] <- "Id";
lang["NAME"]["pl"] <- "Imiê";
lang["PING"]["pl"] <- "Ping";
lang["NO_HELP"]["pl"] <- "Na razie brak pomocy";
