ANIMS <- [
    { menu = 0, name = "ANIM_EGGSCRATCH", instance = "r_scratchegg" },
    { menu = 0, name = "ANIM_HEADSCRATCH", instance = "r_scratchhead" },
    { menu = 0, name = "ANIM_LEGSHAKE", instance = "r_legshake" },
    { menu = 0, name = "ANIM_HGUARD", instance = "s_hguard" },
    { menu = 0, name = "ANIM_STARTSIT", instance = "T_STAND_2_SIT" },
    { menu = 1, name = "ANIM_LGUARD", instance = "s_lguard" },
    { menu = 1, name = "ANIM_PEE", instance = "s_pee" },
    { menu = 1, name = "ANIM_WATCHFIGHT", instance = "s_watchfight" },
    { menu = 1, name = "ANIM_COMEOVERHERE", instance = "t_comeoverhere" },
    { menu = 2, name = "ANIM_DANCE", instance = "t_dance_01" },
    { menu = 2, name = "ANIM_DONTKNOW", instance = "t_dontknow" },
    { menu = 2, name = "ANIM_GETLOST", instance = "t_getlost" },
    { menu = 2, name = "ANIM_GREETCOOL", instance = "t_greetcool" },
    { menu = 3, name = "ANIM_GREETGRD", instance = "t_greetgrd" },
    { menu = 3, name = "ANIM_GREETNOV", instance = "t_greetnov" },
    { menu = 3, name = "ANIM_IGETYOU", instance = "t_igetyou" },
    { menu = 3, name = "ANIM_NO", instance = "t_no" },
    { menu = 4, name = "ANIM_YES", instance = "t_yes" },
    { menu = 4, name = "ANIM_WATCHFIGHT_OHNO", instance = "t_watchfight_ohno" },
    { menu = 4, name = "ANIM_WATCHFIGHT_YEAH", instance = "t_watchfight_yeah" },
    { menu = 4, name = "ANIM_SEARCH", instance = "t_Search" },
    { menu = 5, name = "ANIM_SIT", instance = "s_Sit" }
];