local ANI_NAMES = [{name = "Egg scratch", instance = "r_scratchegg"},
                    {name = "Head scratch", instance = "r_scratchhead"},
                    {name = "Leg shake", instance = "r_legshake"},
                    {name = "Stand as guard <l>", instance = "s_hguard"},
                    {name = "Stand as guard x", instance = "s_lguard"},
                    {name = "Pee", instance = "s_pee"},
                    {name = "Watch fight", instance = "s_watchfight"},
                    {name = "Come over here", instance = "t_comeoverhere"},
                    {name = "Dance", instance = "t_dance_01"},
                    {name = "I don't know", instance = "t_dontknow"},
                    {name = "Get lost", instance = "t_getlost"},
                    {name = "Greet cool", instance = "t_greetcool"},
                    {name = "Greet as guard", instance = "t_greetgrd"},
                    {name = "Greet as novice", instance = "t_greetnov"},
                    {name = "I'll get you", instance = "t_igetyou"},
                    {name = "No", instance = "t_no"},
                    {name = "Yes", instance = "t_yes"},
                    {name = "Facepalm", instance = "t_watchfight_ohno"},
                    {name = "Yeah", instance = "t_watchfight_yeah"},
                    {name = "Search", instance = "t_Search"},
                    {name = "Sit", instance = "s_Sit"}
                    ];